namespace Phlox.API.Services;

/// <summary>
/// Service for cleaning HTML content, extracting text, and processing images.
/// </summary>
public interface IHtmlContentCleanerService
{
    /// <summary>
    /// Cleans HTML content by removing tags, extracting text, and processing images.
    /// Images are described using AI vision and their descriptions are included in the result.
    /// </summary>
    /// <param name="htmlContent">The HTML content to clean.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A result containing cleaned text and image descriptions.</returns>
    Task<HtmlCleaningResult> CleanHtmlAsync(string htmlContent, CancellationToken cancellationToken = default);
}

/// <summary>
/// Result of HTML content cleaning operation.
/// </summary>
public class HtmlCleaningResult
{
    /// <summary>
    /// The cleaned text content with HTML tags removed.
    /// </summary>
    public required string CleanedText { get; set; }

    /// <summary>
    /// Descriptions of images found in the HTML, generated by AI vision.
    /// </summary>
    public List<ImageDescription> ImageDescriptions { get; set; } = [];

    /// <summary>
    /// Gets all content paragraphs including text and image descriptions.
    /// </summary>
    public List<string> GetAllContentParagraphs()
    {
        var paragraphs = new List<string>();

        if (!string.IsNullOrWhiteSpace(CleanedText))
        {
            paragraphs.Add(CleanedText);
        }

        foreach (var imageDesc in ImageDescriptions)
        {
            if (!string.IsNullOrWhiteSpace(imageDesc.Description))
            {
                paragraphs.Add($"[Image: {imageDesc.Description}]");
            }
        }

        return paragraphs;
    }
}

/// <summary>
/// Description of an image extracted from HTML content.
/// </summary>
public class ImageDescription
{
    /// <summary>
    /// The original source of the image (URL or base64).
    /// </summary>
    public required string Source { get; set; }

    /// <summary>
    /// The alt text from the HTML img tag, if available.
    /// </summary>
    public string? AltText { get; set; }

    /// <summary>
    /// AI-generated description of the image content.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Position of the image in the original HTML content.
    /// </summary>
    public int Position { get; set; }
}
